#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scan the audio folders and regenerate manifest.js for the demo page.

Usage:
    python build_manifest.py

Expected layout (relative to this script):

    data_size/1h/              zh_<id>.wav, en_<id>.wav   (2 Mandarin + 2 English)
    hop_size/hop256/
    Feature_Dimension/1/
    Codebook size_VQAE/256/
    RVQ_AE/N1/
    origin/                    the un-coded source recordings, same file names

Rules:
  * The utterance IDs are taken from the reference setting of each factor
    (the first one that has files); Mandarin columns come first, then English.
  * Every setting is looked up by ID, so the same sentence lines up across rows.
  * A trailing " (1)" in a file name (browser download duplicate) is ignored
    when matching IDs, but the real file name is used in the path.
  * origin/ supplies the Ground-truth row.

Re-run this after adding, replacing or renaming any .wav file.
"""

import json
import os
import re
import urllib.parse
from datetime import datetime

ROOT = os.path.dirname(os.path.abspath(__file__))

# (factor key, folder name, [(subfolder, label), ...])
FACTORS = [
    ("data_size", "data_size", [
        ("1h", "1"), ("10h", "10"), ("100h", "100"),
        ("1000h", "1,000"), ("10000h", "10,000"),
    ]),
    ("hop_size", "hop_size", [
        ("hop256", "256"), ("hop512", "512"), ("hop1024", "1024"),
        ("hop2048", "2048"), ("hop4096", "4096"), ("hop8192", "8192"),
    ]),
    ("dimension", "Feature_Dimension", [
        ("1", "1"), ("4", "4"), ("16", "16"), ("64", "64"), ("192", "192"),
    ]),
    ("codebook", "Codebook size_VQAE", [
        ("256", "256"), ("512", "512"), ("1024", "1024"),
        ("2048", "2048"), ("4096", "4096"),
    ]),
    ("rvq", "RVQ_AE", [
        ("N1", "1"), ("N4", "4"), ("N8", "8"), ("N16", "16"),
    ]),
]

GT_DIR = "origin"
LANG_ORDER = ("zh", "en")
LANG_NAME = {"zh": "Mandarin", "en": "English"}
PAT = re.compile(r"^(zh|en)_(\d+)(?:\s*\(\d+\))?\.wav$", re.IGNORECASE)


def scan(folder):
    """{'zh': {id: filename}, 'en': {...}} for one folder."""
    out = {"zh": {}, "en": {}}
    abs_dir = os.path.join(ROOT, folder)
    if not os.path.isdir(abs_dir):
        return None
    for fn in sorted(os.listdir(abs_dir)):
        m = PAT.match(fn)
        if m:
            out[m.group(1).lower()].setdefault(m.group(2), fn)
    return out


def url(*parts):
    return "/".join(urllib.parse.quote(p) for p in parts)


def main():
    manifest = {"generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "factors": {}}
    warnings = []

    gt = scan(GT_DIR) or {"zh": {}, "en": {}}
    if not gt["zh"] and not gt["en"]:
        warnings.append("EMPTY    %s/ has no wav files -- Ground-truth row will be blank" % GT_DIR)

    for key, folder, settings in FACTORS:
        scanned = {}
        for sub, _label in settings:
            s = scan(os.path.join(folder, sub))
            if s is None:
                warnings.append("NO DIR   %s/%s" % (folder, sub))
                s = {"zh": {}, "en": {}}
            elif not s["zh"] and not s["en"]:
                warnings.append("EMPTY    %s/%s has no wav files" % (folder, sub))
            scanned[sub] = s

        # column order: every ID seen in this factor, Mandarin first
        columns = []
        for lang in LANG_ORDER:
            ids = sorted({i for sub, _ in settings for i in scanned[sub][lang]})
            for n, uid in enumerate(ids, 1):
                columns.append({
                    "lang": lang,
                    "id": uid,
                    "label": "%s %d" % (LANG_NAME[lang], n) if len(ids) > 1
                             else LANG_NAME[lang],
                })

        entry = {"columns": columns, "gt": {}, "settings": {}}

        for col in columns:
            fn = gt[col["lang"]].get(col["id"])
            entry["gt"][col["id"]] = url(GT_DIR, fn) if fn else None
            if not fn:
                warnings.append("NO GT    %s/%s_%s.wav missing"
                                % (GT_DIR, col["lang"], col["id"]))

        for sub, _label in settings:
            cells = {}
            for col in columns:
                fn = scanned[sub][col["lang"]].get(col["id"])
                if fn:
                    cells[col["id"]] = url(folder, sub, fn)
                else:
                    cells[col["id"]] = None
                    warnings.append("MISSING  %s/%s/%s_%s.wav"
                                    % (folder, sub, col["lang"], col["id"]))
            entry["settings"][sub] = cells

        manifest["factors"][key] = entry

    js = ("// AUTO-GENERATED by build_manifest.py -- do not edit by hand.\n"
          "window.DEMO_MANIFEST = " +
          json.dumps(manifest, indent=2, ensure_ascii=False) + ";\n")
    with open(os.path.join(ROOT, "manifest.js"), "w", encoding="utf-8") as f:
        f.write(js)

    print("manifest.js written (%s)" % manifest["generated"])
    if warnings:
        print("\n%d issue(s):" % len(warnings))
        for w in warnings:
            print("  " + w)
    else:
        print("no issues -- every setting has all utterances.")


if __name__ == "__main__":
    main()
